# ---------------------
# --- Project Paths ---
# ---------------------

paths:
  data_raw: "data/raw"
  data_metadata: "data/metadata"
  data_processed: "data/processed"
  
  results: "results"
  logs: "results/logs"

  figures: "results/figures"
  models: "results/models"
  tables: "results/tables"


dataset:
  study_name: "LloydPrice_2019"
  body_site: "stool"
  min_prevalence: 0.1

preprocessing:
  min_prevalence: 0.1
  transformation: "log1p" #or "clr"

# ------------------
# --- Parameters ---
# ------------------

params:
  threads: 8
