# ---------------------
# --- Project Paths ---
# ---------------------

paths:
  data_raw: "data/raw"
  data_metadata: "data/metadata"
  data_processed: "data/processed"

  results: "results"
  logs: "results/logs"

  figures: "results/figures"
  models: "results/models"
  tables: "results/tables"


# ----------------
# --- Dataset ----
# ----------------

dataset:
  study_name: "HMP_2019_ibdmdb"
  body_site: "stool"


# ----------------
# --- Metadata ---
# ----------------

metadata:
  sample_id_column: "sample_id"
  disease_column: "study_condition"
  healthy_label: "control"
  ibd_label: "IBD"


# ---------------------
# --- Preprocessing ---
# ---------------------

preprocessing:
  min_prevalence: 0.1
  transformation: "log1p" # or "clr"


# ------------------
# --- Parameters ---
# ------------------

params:
  threads: 8