# ---------------------
# --- Project Paths ---
# ---------------------
paths:
  data_raw: "data/raw"
  data_metadata: "data/metadata"
  data_processed: "data/processed"

  results: "results"
  logs: "results/logs"

  figures: "results/figures"
  models: "results/models"
  tables: "results/tables"


# ----------------
# --- Dataset ----
# ----------------
dataset:
  study_name: "HMP_2019_ibdmdb"
  body_site: "stool"


# ----------------
# --- Metadata ---
# ----------------
metadata:
  sample_id_column: "sample_id"
  disease_column: "study_condition"
  healthy_label: "control"
  ibd_label: "IBD"


# ---------------------
# --- Preprocessing ---
# --------------------
preprocessing:
  min_prevalence: 0.1
  transformation: "log1p"
  pseudocount: 1.0


# -----------------
# --- Diversity ---
# -----------------
diversity:
  calculate_chao1: true
  metrics:
    - richness
    - shannon
    - simpson
    - invsimpson
    - chao1


# -------------------
# --- Ordination ---
# -------------------
ordination:
  pca_scale: false


# ------------------------------
# --- Differential abundance ---
# ------------------------------
differential_abundance:
  p_adjust_method: "BH"
  ntop_features: 20


# ----------------------
# --- Classification ---
# ----------------------
classification:
  seed: 123
  test_fraction: 0.25
  positive_class: "IBD"
  ntop_features: 20
  cross_validation:
    folds: 5
    repeats: 3


# ----------------
# --- Plotting ---
# ----------------
plotting:
  width: 8
  height: 6
  dpi: 300
  max_label_words_taxa: 2
  max_label_words_pathways: 3


# ------------------
# --- Parameters ---
# ------------------
params:
  threads: 8