# schemas/config.schema.yaml

$schema: "http://json-schema.org/draft-07/schema#"


type: object

required:
  - paths
  - dataset
  - preprocessing
  - params

properties:
  paths:
    type: object
    required:
      - data_raw
      - data_metadata
      - data_processed
      - results
      - logs
      - figures
      - models
      - tables
    
    properties:
      data_raw:
        type: string
      data_metadata:
        type: string
      data_processed:
        type: string
      results:
        type: string
      logs:
        type: string
      figures:
        type: string
      models:
        type: string
      tables:
        type: string
  
  dataset:
    type: object
    required: 
      - study_name
      - body_site
      - min_prevalence
    properties:
      study_name:
        type: string
      body_site:
        type: string
      min_prevalence:
        type: integer

  preprocessing:
    type: object
    required:
      - min_prevalence
      - transformation
    properties:
      min_prevalence: 
        type: integer
        minimum: 0.1
      transformation:
        type: integer

  
  params:
    type: object
    required:
      - threads
    properties:
      threads:
        type: integer
        minimum: 1
    